exclude: ^(uv\.lock|package-lock\.json)$
fail_fast: false
repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.12.0  # or the latest
  hooks:
    - id: commitizen
      stages: [commit-msg]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch  # prevent direct commits to main branch
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: check-json
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
    exclude: '^docs/'
  - id: trailing-whitespace
  - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    exclude: ^docs/src/release_notes.md$
    args: [--write-changes]
    additional_dependencies:
      - tomli

- repo: https://github.com/jsh9/pydoclint
  rev: 0.5.15
  hooks:
    - id: pydoclint
      args: [--config=pyproject.toml]

- repo: local
  hooks:
  - id: lint
    name: Lint
    entry: uv run ruff check --fix
    types: [python]
    language: system
    pass_filenames: true
    exclude: ^(migrations/|scripts/)
  - id: format
    name: format
    entry: uv run ruff format
    types: [python]
    language: system
    pass_filenames: true
    exclude: ^(migrations/|scripts/)
  - id: typecheck
    name: Typecheck
    entry: uv run pyright
    types: [python]
    language: system
    pass_filenames: true
    exclude: ^(migrations/|scripts/)
